version: "3.10"
   
services:

  backend:
    build: ./backend
    container_name: 'gunicorn_backend'
    volumes:
      - static_volume:/usr/src/app/backend/staticfiles
      - media_volume:/usr/src/app/backend/media
    expose:
      - 8000
    env_file:
      - backend/.env.prod
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.0-alpine
    container_name: 'database'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/.env.prod.db

  nginx:
    build: ./backend/nginx
    container_name: 'nginx'
    restart: always
    volumes:
      - static_volume:/usr/src/app/backend/staticfiles
      - media_volume:/usr/src/app/backend/media
    ports:
      - 1337:80
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    container_name: 'redis'
    restart: always

volumes:

  postgres_data:
  static_volume:
  media_volume: