# Generated by Django 4.0.8 on 2023-04-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsSpecializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование специализации доктора')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления специализации')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления специализации')),
            ],
            options={
                'verbose_name': 'специализацию',
                'verbose_name_plural': 'Специализации',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя доктора')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации доктора')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления данных доктора')),
                ('specialization_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polyclinic.doctorsspecializations', verbose_name='Специализация доктора')),
            ],
            options={
                'verbose_name': 'врача',
                'verbose_name_plural': 'Врачи',
                'ordering': ('name',),
            },
        ),
    ]
